/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ColorChooseDialog.java
 *
 * Created on 2010-4-9, 12:03:49
 */

package com.cic.datacrawl.ui.dialog;

import java.awt.Color;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;

import javax.swing.JColorChooser;

import com.cic.datacrawl.core.config.Config;
import com.cic.datacrawl.ui.utils.SwingUtil;

/**
 * 
 * @author rex.wu
 */
public class ChooseColorDialog extends javax.swing.JDialog {

	/** Creates new form ColorChooseDialog */
	public ChooseColorDialog(java.awt.Frame parent, String title, boolean modal) {
		super(parent, title, modal);
		initColor();
		initComponents();
	}

	private Color clickColor;
	private Color baseColor;

	private KeyAdapter escKeyListener = new KeyAdapter() {
		@Override
		public void keyPressed(KeyEvent ke) {
			int code = ke.getKeyCode();
			if (code == KeyEvent.VK_ESCAPE) {
				ke.consume();
				setVisible(false);
			}
		}
	};

	private void addEscKeyListener() {
		addKeyListener(escKeyListener);
		btnAccept.addKeyListener(escKeyListener);
		btnBaseColor.addKeyListener(escKeyListener);
		btnCancel.addKeyListener(escKeyListener);

		btnClickColor.addKeyListener(escKeyListener);
		btnReset.addKeyListener(escKeyListener);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {
		java.awt.GridBagConstraints gridBagConstraints;

		jPanel1 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		btnBaseColor = new javax.swing.JButton();
		btnClickColor = new javax.swing.JButton();
		jPanel2 = new javax.swing.JPanel();
		btnReset = new javax.swing.JButton();
		btnAccept = new javax.swing.JButton();
		btnCancel = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setMinimumSize(new java.awt.Dimension(200, 200));
		setName("Form"); // NOI18N
		setResizable(false);
		setLayout(new java.awt.GridBagLayout());

		jPanel1.setBorder(javax.swing.BorderFactory
				.createTitledBorder("Choose Color")); // NOI18N
		jPanel1.setMaximumSize(new java.awt.Dimension(164, 46));
		jPanel1.setName("jPanel1"); // NOI18N
		jPanel1.setLayout(new java.awt.GridBagLayout());

		jLabel1.setText("Click Color:"); // NOI18N
		jLabel1.setName("jLabel1"); // NOI18N
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
		gridBagConstraints.weightx = 0.5;
		gridBagConstraints.insets = new java.awt.Insets(6, 5, 4, 1);
		jPanel1.add(jLabel1, gridBagConstraints);

		jLabel2.setText("Base Color"); // NOI18N
		jLabel2.setName("jLabel2"); // NOI18N
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.gridheight = java.awt.GridBagConstraints.REMAINDER;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
		gridBagConstraints.weightx = 0.5;
		gridBagConstraints.insets = new java.awt.Insets(1, 5, 3, 1);
		jPanel1.add(jLabel2, gridBagConstraints);

		btnBaseColor.setBackground(baseColor);
		btnBaseColor.setText(" "); // NOI18N
		btnBaseColor.setBorder(javax.swing.BorderFactory.createEmptyBorder(1,
				1, 1, 1));
		btnBaseColor.setName("btnBaseColor"); // NOI18N
		btnBaseColor.setPreferredSize(new java.awt.Dimension(17, 17));
		btnBaseColor.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnBaseColorActionPerformed(evt);
			}
		});
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
		gridBagConstraints.gridheight = java.awt.GridBagConstraints.REMAINDER;
		gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
		gridBagConstraints.weightx = 0.2;
		gridBagConstraints.weighty = 1.0;
		gridBagConstraints.insets = new java.awt.Insets(1, 2, 3, 5);
		jPanel1.add(btnBaseColor, gridBagConstraints);

		btnClickColor.setBackground(clickColor);
		btnClickColor.setText(" "); // NOI18N
		btnClickColor.setBorder(null);
		btnClickColor.setName("btnClickColor"); // NOI18N
		btnClickColor.setPreferredSize(new java.awt.Dimension(17, 17));
		btnClickColor.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnClickColorActionPerformed(evt);
			}
		});
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 0;
		gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
		gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
		gridBagConstraints.weightx = 0.2;
		gridBagConstraints.weighty = 1.0;
		gridBagConstraints.insets = new java.awt.Insets(6, 2, 4, 5);
		jPanel1.add(btnClickColor, gridBagConstraints);

		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 0;
		gridBagConstraints.weightx = 1.0;
		gridBagConstraints.weighty = 1.0;
		gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
		gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
		getContentPane().add(jPanel1, gridBagConstraints);

		jPanel2.setName("jPanel2"); // NOI18N
		jPanel2.setLayout(new java.awt.GridBagLayout());

		btnReset.setText("Reset"); // NOI18N
		btnReset.setName("btnReset"); // NOI18N
		btnReset.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnResetActionPerformed(evt);
			}
		});
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridheight = java.awt.GridBagConstraints.REMAINDER;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
		gridBagConstraints.insets = new java.awt.Insets(5, 3, 5, 3);
		jPanel2.add(btnReset, gridBagConstraints);

		btnAccept.setText("Accept"); // NOI18N
		btnAccept.setName("btnAccept"); // NOI18N
		btnAccept.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnAcceptActionPerformed(evt);
			}
		});
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridheight = java.awt.GridBagConstraints.REMAINDER;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
		gridBagConstraints.insets = new java.awt.Insets(5, 3, 5, 3);
		jPanel2.add(btnAccept, gridBagConstraints);

		btnCancel.setText("Cancel"); // NOI18N
		btnCancel.setName("btnCancel"); // NOI18N
		btnCancel.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnCancelActionPerformed(evt);
			}
		});
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
		gridBagConstraints.gridheight = java.awt.GridBagConstraints.REMAINDER;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
		gridBagConstraints.insets = new java.awt.Insets(5, 3, 5, 3);
		jPanel2.add(btnCancel, gridBagConstraints);

		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.weightx = 1.0;
		gridBagConstraints.weighty = 1.0;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 5);
		getContentPane().add(jPanel2, gridBagConstraints);
		addEscKeyListener();
		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnResetActionPerformed
		initColor();
		btnClickColor.setBackground(clickColor);
		btnBaseColor.setBackground(baseColor);
	}// GEN-LAST:event_btnResetActionPerformed

	private void btnAcceptActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnAcceptActionPerformed
		saveColor();
		this.setVisible(false);
	}// GEN-LAST:event_btnAcceptActionPerformed

	private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnCancelActionPerformed
		initColor();
		this.setVisible(false);
	}// GEN-LAST:event_btnCancelActionPerformed

	private void btnClickColorActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnClickColorActionPerformed
		clickColor = JColorChooser.showDialog(this, "Choose Click Color",
				clickColor);
		btnClickColor.setBackground(clickColor);
	}// GEN-LAST:event_btnClickColorActionPerformed

	private void btnBaseColorActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnBaseColorActionPerformed
		baseColor = JColorChooser.showDialog(this, "Choose Base Color",
				baseColor);
		btnBaseColor.setBackground(baseColor);
	}// GEN-LAST:event_btnBaseColorActionPerformed

	private void initColor() {
		clickColor = SwingUtil.parseToColor(Config.getInstance()
				.getClickColor());
		baseColor = SwingUtil.parseToColor(Config.getInstance().getBaseColor());
	}

	private void saveColor() {
		Config.getInstance().setClickColor(
				""
						+ (clickColor.getRed() * 65536 + clickColor.getGreen()
								* 256 + clickColor.getBlue()));

		Config.getInstance().setBaseColor(
				""
						+ (baseColor.getRed() * 65536 + baseColor.getGreen()
								* 256 + baseColor.getBlue()));
	}

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				ChooseColorDialog dialog = new ChooseColorDialog(
						new javax.swing.JFrame(), "", true);
				dialog.addWindowListener(new java.awt.event.WindowAdapter() {
					public void windowClosing(java.awt.event.WindowEvent e) {
						System.exit(0);
					}
				});
				dialog.setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton btnAccept;
	private javax.swing.JButton btnBaseColor;
	private javax.swing.JButton btnCancel;
	private javax.swing.JButton btnClickColor;
	private javax.swing.JButton btnReset;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	// End of variables declaration//GEN-END:variables

}
