/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ChooseFolderDialog.java
 *
 * Created on 2010-1-13, 14:51:20
 */

package com.cic.datacrawl.ui.dialog;

import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;

import javax.swing.event.TreeSelectionEvent;
import javax.swing.event.TreeSelectionListener;
import javax.swing.tree.DefaultMutableTreeNode;


/**
 * 
 * @author rex.wu
 */
public class ChooseFolderDialog extends javax.swing.JDialog {

	/**
	 * 
	 */
	private static final long serialVersionUID = -9008347386862934652L;
	private ChooseWorkspaceDialog parentDialog;
	private String path;

	/** Creates new form ChooseFolderDialog */
	public ChooseFolderDialog(ChooseWorkspaceDialog parent) {
		super(parent);
		parentDialog = parent;
		initComponents();
	}


	private KeyAdapter escKeyListener = new KeyAdapter() {
		@Override
		public void keyPressed(KeyEvent ke) {
			int code = ke.getKeyCode();
			if (code == KeyEvent.VK_ESCAPE) {
				ke.consume();
				setVisible(false);
			}
		}
	};

	private void addEscKeyListener() {
		addKeyListener(escKeyListener);
		

		
		
		btnCancel.addKeyListener(escKeyListener);
		btnOK.addKeyListener(escKeyListener);
		folderTreeScrollPane.addKeyListener(escKeyListener);
		jTextField1.addKeyListener(escKeyListener);
		
	}
	
	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {
		java.awt.GridBagConstraints gridBagConstraints;

		jLabel1 = new javax.swing.JLabel();
		folderTreeScrollPane = new FolderTreeScrollPane();
		jTextField1 = new javax.swing.JTextField();
		jLabel2 = new javax.swing.JLabel();
		btnOK = new javax.swing.JButton();
		btnCancel = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setTitle("Select Workspace Directory"); // NOI18N
		setName("Form"); // NOI18N
		setResizable(false);
		getContentPane().setLayout(new java.awt.GridBagLayout());

		jLabel1.setText("Select the workspace directory to use."); // NOI18N
		jLabel1.setName("jLabel1"); // NOI18N
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridwidth = 3;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		gridBagConstraints.weightx = 1.0;
		gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
		getContentPane().add(jLabel1, gridBagConstraints);

		folderTreeScrollPane.addTreeSelectionListener(new TreeSelectionListener() {

			@Override
			public void valueChanged(TreeSelectionEvent e) {
				DefaultMutableTreeNode node = folderTreeScrollPane.getTreeNode(e
						.getPath());
				FileNode fnode = folderTreeScrollPane.getFileNode(node);
				if (fnode != null) {
					String name = fnode.getFile().getName();
					if(name == null || name.trim().length() == 0){
						name = fnode.getFile().getAbsolutePath();
					}
					jTextField1.setText(name);
					path=fnode.getFile().getAbsolutePath();
				} else {
					path="";
					jTextField1.setText("");
				}
			}
		});

		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.gridwidth = 3;
		gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
		gridBagConstraints.weightx = 1.0;
		gridBagConstraints.weighty = 1.0;
		gridBagConstraints.insets = new java.awt.Insets(3, 5, 0, 5);
		getContentPane().add(folderTreeScrollPane, gridBagConstraints);

		jTextField1.setEditable(false);
		jTextField1.setText(""); // NOI18N
		jTextField1.setAutoscrolls(false);
		jTextField1.setName("jTextField1"); // NOI18N
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 2;
		gridBagConstraints.gridwidth = 2;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		gridBagConstraints.weightx = 1.0;
		gridBagConstraints.insets = new java.awt.Insets(3, 3, 0, 5);
		getContentPane().add(jTextField1, gridBagConstraints);

		jLabel2.setText("Folder name:"); // NOI18N
		jLabel2.setName("jLabel2"); // NOI18N
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 2;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
		gridBagConstraints.insets = new java.awt.Insets(3, 5, 0, 0);
		getContentPane().add(jLabel2, gridBagConstraints);

		btnOK.setText("Confirm"); // NOI18N
		btnOK.setName("btnOK"); // NOI18N
		btnOK.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnOKActionPerformed(evt);
			}
		});
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 3;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
		gridBagConstraints.insets = new java.awt.Insets(3, 120, 5, 0);
		getContentPane().add(btnOK, gridBagConstraints);

		btnCancel.setText("Cancel"); // NOI18N
		btnCancel.setName("btnCancel"); // NOI18N
		btnCancel.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnCancelActionPerformed(evt);
			}
		});
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 2;
		gridBagConstraints.gridy = 3;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
		gridBagConstraints.insets = new java.awt.Insets(3, 3, 5, 5);
		getContentPane().add(btnCancel, gridBagConstraints);

		addEscKeyListener();
		
		pack();
		java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit()
				.getScreenSize();
		java.awt.Dimension dialogSize = getSize();
		setLocation((screenSize.width - dialogSize.width) / 2,
				(screenSize.height - dialogSize.height) / 2);
		
		
	}// </editor-fold>//GEN-END:initComponents

	private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnOKActionPerformed
		parentDialog.setPath(path);
		this.setVisible(false);
	}// GEN-LAST:event_btnOKActionPerformed

	private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnCancelActionPerformed
		this.setVisible(false);
	}// GEN-LAST:event_btnCancelActionPerformed

	public void showSelectPath(String path){
		folderTreeScrollPane.show(path);
	}
	
	/**
	 * @param args
	 *            the command line arguments
	 */
	/*
	 * public static void main(String args[]) {
	 * java.awt.EventQueue.invokeLater(new Runnable() { public void run() {
	 * ChooseFolderDialog dialog = new ChooseFolderDialog( new
	 * javax.swing.JFrame(), true); dialog.addWindowListener(new
	 * java.awt.event.WindowAdapter() { public void
	 * windowClosing(java.awt.event.WindowEvent e) { System.exit(0); } });
	 * dialog.setVisible(true); } }); }
	 */

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton btnCancel;
	private javax.swing.JButton btnOK;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private FolderTreeScrollPane folderTreeScrollPane;
	private javax.swing.JTextField jTextField1;
	// End of variables declaration//GEN-END:variables

}
